### ISSUE TITLE
error - ionic cordova plugin add

### ISSUE THREAD

**Issue by mathritter** [yasirkula/UnityIonicIntegration#33]
When I run the command: 
ionic cordova plugin add https://github.com/yasirkula/UnityIonicIntegration.git , 

I get this error: 

(node:4992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to fetch plugin https://github.com/yasirkula/UnityIonicIntegration.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! git clone C:\Users\Matheus\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-yasirkula-UnityIonicIntegration-git-ef48a645 C:\Users\Matheus\AppData\Local\Temp\npm-5728-9761bbd4\git-cache-0cccc512\672026213463920fbdcf49ec2bac6e56fb19b1c0: Cloning into 'C:\Users\Matheus\AppData\Local\Temp\npm-5728-9761bbd4\git-cache-0cccc512\672026213463920fbdcf49ec2bac6e56fb19b1c0'...
npm ERR! git clone C:\Users\Matheus\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-yasirkula-UnityIonicIntegration-git-ef48a645 C:\Users\Matheus\AppData\Local\Temp\npm-5728-9761bbd4\git-cache-0cccc512\672026213463920fbdcf49ec2bac6e56fb19b1c0: git-upload-pack 'C:\Users\Matheus\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-yasirkula-UnityIonicIntegration-git-ef48a645': git-upload-pack: command not found
npm ERR! git clone C:\Users\Matheus\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-yasirkula-UnityIonicIntegration-git-ef48a645 C:\Users\Matheus\AppData\Local\Temp\npm-5728-9761bbd4\git-cache-0cccc512\672026213463920fbdcf49ec2bac6e56fb19b1c0: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\Matheus\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-yasirkula-UnityIonicIntegration-git-ef48a645 C:\Users\Matheus\AppData\Local\Temp\npm-5728-9761bbd4\git-cache-0cccc512\672026213463920fbdcf49ec2bac6e56fb19b1c0:
npm ERR! git clone C:\Users\Matheus\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-yasirkula-UnityIonicIntegration-git-ef48a645 C:\Users\Matheus\AppData\Local\Temp\npm-5728-9761bbd4\git-cache-0cccc512\672026213463920fbdcf49ec2bac6e56fb19b1c0: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\Matheus\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-yasirkula-UnityIonicIntegration-git-ef48a645 C:\Users\Matheus\AppData\Local\Temp\npm-5728-9761bbd4\git-cache-0cccc512\672026213463920fbdcf49ec2bac6e56fb19b1c0: and the repository exists.
npm ERR! git clone C:\Users\Matheus\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-yasirkula-UnityIonicIntegration-git-ef48a645 C:\Users\Matheus\AppData\Local\Temp\npm-5728-9761bbd4\git-cache-0cccc512\672026213463920fbdcf49ec2bac6e56fb19b1c0:
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/yasirkula/UnityIonicIntegration.git" "--production" "--save"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\Matheus\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-yasirkula-UnityIonicIntegration-git-ef48a645 C:\Users\Matheus\AppData\Local\Temp\npm-5728-9761bbd4\git-cache-0cccc512\672026213463920fbdcf49ec2bac6e56fb19b1c0
npm ERR! Cloning into 'C:\Users\Matheus\AppData\Local\Temp\npm-5728-9761bbd4\git-cache-0cccc512\672026213463920fbdcf49ec2bac6e56fb19b1c0'...
npm ERR! git-upload-pack 'C:\Users\Matheus\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-yasirkula-UnityIonicIntegration-git-ef48a645': git-upload-pack: command not found
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Desenvolvimento\workspace\anime-buzz-mobile\animebuzz-mobile\npm-debug.log

**Comment by yasirkula** [comment]
Try this one: `ionic cordova plugin add https://github.com/yasirkula/UnityIonicIntegration.git --nofetch`

Source: https://github.com/katzer/cordova-plugin-local-notifications/issues/1345

**Comment by mathritter** [comment]
Now I get this:

`PS D:\Desenvolvimento\workspace\anime-buzz-mobile\animebuzz-mobile> ionic cordova plugin add https://github.com/yasirkula/UnityIonicIntegration.git --nofetch
> cordova plugin add https://github.com/yasirkula/UnityIonicIntegration.git --save
(node:13708) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/yasirkula/UnityIonicIntegration.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matheus\AppData\Roaming\npm-cache\_logs\2018-07-23T20_36_45_904Z-debug.log
    at C:\Users\Matheus\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\Matheus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\Matheus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\Matheus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\Matheus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\Matheus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\Matheus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\Matheus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:13708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by mathritter** [comment]
I tried the post you mentioned, tried upgrading my npm and nvm.

**Comment by mathritter** [comment]
Now I tried installing x86 nodejs, didn't work

**Comment by mathritter** [comment]
I guess I fixed it, I executed the command thru the git bash, now I'm gonna follow the rest of the tut. I will close the issue as soon as I make it work. By the way I don't get it, is this repository about running a unity project inside an ionic app. I don't get it, where do I put the unity compiled project? I feel something is missing

**Comment by yasirkula** [comment]
Yes it is about running a Unity project inside an Ionic app. You can put your Unity project anywhere outside of your Ionic project.
