### ISSUE TITLE
app crash when try to open unity

### ISSUE THREAD

**Issue by essec** [yasirkula/UnityIonicIntegration#62]
```
W/PluginManager: THREAD WARNING: exec() call to LaunchAR.launchAR blocked the main thread for 33ms. Plugin should use CordovaInterface.getThreadPool().
D/InputMethodManager: HSIFW - flag : 0 Pid : 10913
D/ViewRootImpl@c4e3021[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@6d9f849[MainActivity]
    getNavigationBarColor() -855310
W/libEGL: EGLNativeWindowType 0x75cc519010 disconnect failed
D/OpenGLRenderer: eglDestroySurface = 0x75acdc2b00, 0x75cc519000
D/ViewRootImpl@c4e3021[MainActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x5 surface={false 0} changed=true
D/ViewRootImpl@c4e3021[MainActivity]: stopped(true) old=false
D/CordovaActivity: Stopped the activity.
D/CordovaActivity: CordovaActivity.onDestroy()
D/CordovaWebViewImpl: >>> loadUrl(about:blank)
W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
D/InputMethodManager: HSIFW - flag : 0 Pid : 10913
D/ViewRootImpl@c4e3021[MainActivity]: dispatchDetachedFromWindow
D/InputTransport: Input channel destroyed: fd=153
W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.a(PG:127)
        at Rf0.loadingStateChanged(PG:2)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (11955) crash detected (code -1).
```
I got this error

**Comment by yasirkula** [comment]
Does it happen when launching Unity the first time, or after closing it once and then reopening it? Does it always crash or occasionally?

**Comment by essec** [comment]
it always crash sir

**Comment by essec** [comment]
I found this problem because cordova-sqlite-storage plugin. So I remove it your plugin WORK!!! Thank you.
