### ISSUE TITLE
App crashing on startup

### ISSUE THREAD

**Issue by linkedoranean** [yasirkula/UnityIonicIntegration#71]
Hi!

I'm trying to install the plugin and followed all instructions.
But every time I try to run the project, the app crashes.

Here is the logcat:

`2021-04-05 18:00:24.326 19725-19725/? I/o.ionic.starte: Late-enabling -Xcheck:jni
2021-04-05 18:00:24.785 19725-19725/io.ionic.starter W/o.ionic.starte: miui_dex2oat: oat file of /data/app/io.ionic.starter-MdzXuzyIos8PRDy0zgPnxw==/base.apk is not exists
2021-04-05 18:00:24.844 19725-19725/io.ionic.starter I/Perf: Connecting to perf service.
2021-04-05 18:00:24.948 19725-19725/io.ionic.starter E/o.ionic.starte: Invalid ID 0x00000000.
2021-04-05 18:00:24.948 19725-19725/io.ionic.starter D/AndroidRuntime: Shutting down VM
2021-04-05 18:00:24.953 19725-19725/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 19725
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.ionic.starter/com.unity3d.player.UnityPlayerActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:360)
        at android.content.res.MiuiResources.getText(MiuiResources.java:97)
        at android.content.res.Resources.getString(Resources.java:453)
        at com.unity3d.player.UnityPlayer.GetGlViewContentDescription(Unknown Source:20)
        at com.unity3d.player.UnityPlayer.<init>(Unknown Source:256)
        at com.unity3d.player.UnityPlayerActivity.onCreate(UnityPlayerActivity.java:41)
        at android.app.Activity.performCreate(Activity.java:7232)
        at android.app.Activity.performCreate(Activity.java:7221)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2964)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6864) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
2021-04-05 18:00:24.997 19725-19725/io.ionic.starter I/Process: Sending signal. PID: 19725 SIG: 9`

`2021-04-05 18:00:24.953 19725-19725/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 19725
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.ionic.starter/com.unity3d.player.UnityPlayerActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:360)
        at android.content.res.MiuiResources.getText(MiuiResources.java:97)
        at android.content.res.Resources.getString(Resources.java:453)
        at com.unity3d.player.UnityPlayer.GetGlViewContentDescription(Unknown Source:20)
        at com.unity3d.player.UnityPlayer.<init>(Unknown Source:256)
        at com.unity3d.player.UnityPlayerActivity.onCreate(UnityPlayerActivity.java:41)
        at android.app.Activity.performCreate(Activity.java:7232)
        at android.app.Activity.performCreate(Activity.java:7221)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2964)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6864) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) `

**Comment by yasirkula** [comment]
This is probably the most important part of the crash log:

> Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
> at android.content.res.Resources.getText(Resources.java:360)
> at android.content.res.MiuiResources.getText(MiuiResources.java:97)
> at android.content.res.Resources.getString(Resources.java:453)
> at com.unity3d.player.UnityPlayer.GetGlViewContentDescription(Unknown Source:20)
> at com.unity3d.player.UnityPlayer.<init>(Unknown Source:256)
> at com.unity3d.player.UnityPlayerActivity.onCreate(UnityPlayerActivity.java:41)

Does build & running the Unity project without integration cause the same issue?

**Comment by yasirkula** [comment]
Possible solution: https://stackoverflow.com/questions/56416191/resource-not-found-exception-while-opening-unity-project-in-android-studio/56461957

**Comment by linkedoranean** [comment]
> Does build & running the Unity project without integration cause the same issue?

It does not.
I was able to install directly from unity and also export to Android Studio and build directly again.

>Possible solution: https://stackoverflow.com/questions/56416191/resource-not-found-exception-while-opening-unity-project-in-android-studio/56461957

>Same solution, another thread: https://forum.unity.com/threads/unity-2018-3-6-upgrade-to-unity-2018-4-has-bug.681997/

Oh heck!
The first one [adding line to strings.xml] worked haha
But I did came buy another issue:

>2021-04-06 11:42:25.168 4373-4388/? I/ActivityManager: START u0 {act=null typ=null flg=0x0 cmp=ComponentInfo{io.ionic.starter/com.unitycaller.ionic.UnityPlayerExtendedActivity}} from uid 10329
2021-04-06 11:42:25.236 4373-6256/? I/ActivityManager: Start proc 2012:io.ionic.starter:unityselfprocess/u0a329 for activity io.ionic.starter/com.unitycaller.ionic.UnityPlayerExtendedActivity
2021-04-06 11:42:25.241 2012-2012/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=io.ionic.starter:unityselfprocess 
2021-04-06 11:42:25.310 4373-4651/? D/GameManagerService: handleForegroundChange(). pkgName: io.ionic.starter, clsName: com.unitycaller.ionic.UnityPlayerExtendedActivity,FgActivityName:io.ionic.starter/com.unitycaller.ionic.UnityPlayerExtendedActivity
2021-04-06 11:42:25.430 2012-2012/io.ionic.starter E/Unity: Unable to find main
2021-04-06 11:42:25.438 2012-2012/io.ionic.starter E/Unity: Unable to locate player settings. bin/Data/settings.xml
2021-04-06 11:42:25.585 2012-2012/io.ionic.starter D/ViewRootImpl@d0da55d[UnityPlayerExtendedActivity]: setView = DecorView@a1feed2[] TM=true MM=false
2021-04-06 11:42:25.630 2012-2012/io.ionic.starter D/ViewRootImpl@d0da55d[UnityPlayerExtendedActivity]: dispatchAttachedToWindow
2021-04-06 11:42:25.659 4373-6256/? V/WindowManager: Relayout Window{427b261 u0 io.ionic.starter/com.unitycaller.ionic.UnityPlayerExtendedActivity}: viewVisibility=0 req=1024x497 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2 fl=#1820002 fmt=-3 wanim=0x10302fd surfaceInsets=Rect(84, 84 - 84, 84) needsMenuKey=2 colorMode=0 naviIconColor=0}
2021-04-06 11:42:25.667 2012-2012/io.ionic.starter D/ViewRootImpl@d0da55d[UnityPlayerExtendedActivity]: Relayout returned: old=[0,0][0,0] new=[28,743][1052,1240] result=0x1 surface={valid=false 0} changed=false
2021-04-06 11:42:25.672 2012-2012/io.ionic.starter E/ViewRootImpl@d0da55d[UnityPlayerExtendedActivity]: Surface is not valid.
2021-04-06 11:42:25.675 4373-6256/? V/WindowManager: Relayout Window{427b261 u0 io.ionic.starter/com.unitycaller.ionic.UnityPlayerExtendedActivity}: viewVisibility=8 req=1024x497 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2 fl=#1820002 fmt=-3 wanim=0x10302fd surfaceInsets=Rect(84, 84 - 84, 84) needsMenuKey=2 colorMode=0 naviIconColor=0}
2021-04-06 11:42:25.681 2012-2012/io.ionic.starter D/ViewRootImpl@d0da55d[UnityPlayerExtendedActivity]: Relayout returned: old=[28,743][1052,1240] new=[28,743][1052,1240] result=0x1 surface={valid=false 0} changed=false
2021-04-06 11:42:25.713 2012-2012/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter:unityselfprocess, PID: 2012
    java.lang.RuntimeException: Unable to destroy activity {io.ionic.starter/com.unitycaller.ionic.UnityPlayerExtendedActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
        at android.os.Message.sendToTarget(Message.java:418)
        at com.unity3d.player.UnityPlayer$b.a(Unknown Source:8)
        at com.unity3d.player.UnityPlayer$b.a(Unknown Source:2)
        at com.unity3d.player.UnityPlayer.quit(Unknown Source:16)
        at com.unity3d.player.UnityPlayerActivity.onDestroy(Unknown Source:2)
        at com.unitycaller.ionic.UnityPlayerExtendedActivity.onDestroy(UnityPlayerExtendedActivity.java:49)
        at android.app.Activity.performDestroy(Activity.java:7522)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
2021-04-06 11:42:35.704 4373-4406/? W/ActivityManager: Activity destroy timeout for ActivityRecord{d46a0b2 u0 io.ionic.starter/com.unitycaller.ionic.UnityPlayerExtendedActivity t15 f}
